# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}

---
action: create_or_modify
module: policies/pwhistory
position: "cn=pwhistory,cn=users,cn=policies,{{ .ldapBase }}"
properties:
  name: "default-settings"
  pwQualityCheck: True

{{ end }}
