# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}

---
action: create
module: portals/folder
position: cn=folder,cn=portals,cn=univention,{{ .ldapBase }}
properties:
  name: "swp.fileshare_directdoc"
  displayName:
    de_DE: "Erstelle neu in Dateien"
    en_US: "create new in Files"

{{ end }}
