{{ with .Values.stackDataContext }}

---
action: create
module: portals/folder
position: cn=folder,cn=portals,cn=univention,{{ .ldapBase }}
properties:
  name: "swp.fileshare_directdoc"
  displayName:
    de_DE: "Erstelle neue Dateien"
    en_US: "Create new files"

{{ end }}
