# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}
---
action: modify
module: users/user
position: uid=Administrator,cn=users,{{ include "stack-data-swp.ldapBaseDn" $ }}
properties:
  firstname: "Addison"
  mailPrimaryAddress: "admin@{{ include "stack-data-swp.externalMailDomain" $ }}"
---
action: ensure_list_contains
module: users/user
position: uid=Administrator,cn=users,{{ include "stack-data-swp.ldapBaseDn" $ }}
properties:
  mailAlternativeAddress:
    - "abuse@{{ include "stack-data-swp.externalMailDomain" $ }}"
    - "hostmaster@{{ include "stack-data-swp.externalMailDomain" $ }}"
    - "postmaster@{{ include "stack-data-swp.externalMailDomain" $ }}"
    - "system-mails@{{ include "stack-data-swp.externalMailDomain" $ }}"
    - "root@{{ include "stack-data-swp.externalMailDomain" $ }}"
    - "webmaster@{{ include "stack-data-swp.externalMailDomain" $ }}"
{{ end }}
