# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}
{{- $context := . }}

---
action: "create"
module: "groups/group"
position: 'cn=groups,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "LDAPSearch Users"

{{- range .ldapSearchUsers }}
---
action: "create"
module: "users/ldap"
position: "cn=users,{{ include "stack-data-swp.ldapBaseDn" $ }}"
properties:
  username: {{ .username | quote }}
  lastname: {{ .lastname | default "LDAP-Search-User" | quote }}
  password: {{ required "ldapSearchUser.password is missing" .password | quote }}

{{ end }}
{{ end }}
