# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}

---
# Create extended attribute to activate A2GM
action: "create"
module: "settings/extended_attribute"
position: 'cn=custom attributes,cn=univention,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "attribute-to-group-mapper"
  CLIName: "attributeToGroupMapper"
  shortDescription: "Custom Hook to add users to groups dependent on attributes"
  "module": ["users/user"]
  hook: "AttributeToGroupMapper"
  default: ""
  ldapMapping: "univentionFreeAttribute14"
  objectClass: "univentionFreeAttributes"
  multivalue: False
  valueRequired: False
  mayChange: True
  doNotSearch: True
  deleteObjectClass: True
  disableUDMWeb: True

{{end}}
