{{ with .Values.stackDataContext }}

---
# Make OX Tab be openDesk Tab
action: "modify"
module: "settings/extended_attribute"
position: "cn=isOxUser,cn=open-xchange,cn=custom attributes,cn=univention,{{ .ldapBase }}"
properties:
  name: "isOxUser"
  shortDescription: "Groupware (deactivate will delete user data in groupware)"
  translationShortDescription:
    de_DE: "Groupware (Deaktivierung löscht Benutzerdaten in Groupware)"
  longDescription: ""
  translationLongDescription:
    de_DE: ""
  tabName: openDesk
  translationTabName:
    de_DE: openDesk
  groupName: "Berechtigung: Login/Nutzung"

---
# Modify ox-connector user template to be openDesk one
action: "modify"
module: "settings/usertemplate"
position: "cn=open-xchange groupware account,cn=templates,cn=univention,{{ .ldapBase }}"
properties:
  name: "openDesk User"
  opendeskFileshareEnabled: True
  opendeskProjectmanagementEnabled: True
  opendeskKnowledgemanagementEnabled: True
  opendeskLivecollaborationEnabled: True
  opendeskProjectmanagementAdmin: False
  isOxUser: True
  mailPrimaryAddress: "<username>@{{ .externalMailDomain }}"
  e-mail: ["<username>@{{ .externalMailDomain }}"]
  unixhome: "/home/<username>"
  oxDisplayName: "<firstname> <lastname> (<username>)"
  oxAccess: "premium"
  primaryGroup: "cn=Domain Users,cn=groups,{{ .ldapBase }}"

---
# Create admin user template
action: "create"
module: "settings/usertemplate"
position: "cn=templates,cn=univention,{{ .ldapBase }}"
properties:
  name: "openDesk Admin"
  isOxUser: False
  primaryGroup: "cn=Domain Admins,cn=groups,{{ .ldapBase }}"
  opendeskFileshareEnabled: False
  opendeskProjectmanagementEnabled: False
  opendeskKnowledgemanagementEnabled: False
  opendeskLivecollaborationEnabled: False
  opendeskProjectmanagementAdmin: False

{{ end }}
