# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}

---
# Move isOxUser setting to openDesk tab
action: "modify"
module: "settings/extended_attribute"
position: "cn=isOxUser,cn=open-xchange,cn=custom attributes,cn=univention,{{ .ldapBase }}"
properties:
  name: "isOxUser"
  shortDescription: "Groupware (deactivate will delete user data in groupware)"
  translationShortDescription:
    de_DE: "Groupware (Deaktivierung löscht Benutzerdaten in Groupware)"
  longDescription: ""
  translationLongDescription:
    de_DE: ""
  tabName: openDesk
  translationTabName:
    de_DE: openDesk
  groupName: "Berechtigung: Login/Nutzung"

---
# Move isOxGroup setting to openDesk tab
action: "modify"
module: "settings/extended_attribute"
position: "cn=isOxGroup,cn=open-xchange,cn=custom attributes,cn=univention,{{ .ldapBase }}"
properties:
  name: "isOxGroup"
  shortDescription: "Groupware"
  translationShortDescription:
    de_DE: "Groupware"
  longDescription: ""
  translationLongDescription:
    de_DE: ""
  tabName: openDesk
  translationTabName:
    de_DE: openDesk
  groupName: "Gruppe in Komponenten bereitstellen"

---
# Modify ox-connector user template to be openDesk one
action: "modify"
module: "settings/usertemplate"
position: "cn=openDesk User,cn=templates,cn=univention,{{ .ldapBase }}"
properties:
  name: "openDesk User"
  opendeskFileshareEnabled: True
  opendeskProjectmanagementEnabled: True
  opendeskKnowledgemanagementEnabled: True
  opendeskLivecollaborationEnabled: True
  opendeskProjectmanagementAdmin: False
  opendeskFileshareAdmin: False
  isOxUser: True
  mailPrimaryAddress: "<username>@{{ .externalMailDomain }}"
  e-mail: ["<username>@{{ .externalMailDomain }}"]
  unixhome: "/home/<username>"
  oxContext: {{ .oxDefaultContext }}
  oxDisplayName: "<firstname> <lastname> (<username>)"
  oxAccess: "opendesk_standard"
  primaryGroup: "cn=Domain Users,cn=groups,{{ .ldapBase }}"

---
# Create admin user template
action: "create"
module: "settings/usertemplate"
position: "cn=templates,cn=univention,{{ .ldapBase }}"
properties:
  name: "openDesk Admin"
  isOxUser: False
  primaryGroup: "cn=Domain Admins,cn=groups,{{ .ldapBase }}"
  opendeskFileshareEnabled: False
  opendeskProjectmanagementEnabled: False
  opendeskKnowledgemanagementEnabled: False
  opendeskLivecollaborationEnabled: False
  opendeskProjectmanagementAdmin: False
  opendeskFileshareAdmin: False

---
action: "modify"
module: "settings/extended_attribute"
position: "cn=oxAccess,cn=open-xchange,cn=custom attributes,cn=univention,{{ .ldapBase }}"
properties:
  default: "groupware"

---
action: "modify"
module: "settings/extended_attribute"
position: "cn=templateOxAccess,cn=open-xchange,cn=custom attributes,cn=univention,{{ .ldapBase }}"
properties:
  default: "groupware"

{{ end }}
