# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}

---
action: create
module: settings/umc_operationset
position: 'cn=operations,cn=UMC,cn=univention,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "ox-functional-accounts"
  description: "Administration for OX functional mailboxes"
  flavor: "oxmail/functional_account"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=users/user"
    - command: "udm/*"
      option: "objectType=oxmail/functional_account"
---
action: create
module: settings/umc_operationset
position: 'cn=operations,cn=UMC,cn=univention,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "ox-resources"
  description: "Administration for OX resources"
  flavor: "oxresources/oxresources"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=oxresources/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: 'cn=operations,cn=UMC,cn=univention,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "ox-context"
  description: "Administration for OX contexts"
  flavor: "oxmail/oxcontext"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=oxmail/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: 'cn=operations,cn=UMC,cn=univention,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "read-udm-usertemplates"
  description: "Allows read access to user templates (required for creating new users with the wizard)"
  flavor: "settings/usertemplate"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/get"
      option: "objectType=settings/usertemplate"
---
action: create
module: settings/umc_operationset
position: 'cn=operations,cn=UMC,cn=univention,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  name: "read-only-udm-object-for-support"
  description: "Operation set for support with just read-only permission"
  # flavor: ""
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/get"
      option: ""
    - command: "udm/query"
      option: ""
    - command: "udm/layout"
      option: ""
    - command: "udm/properties"
      option: ""
    - command: "udm/reports/query"
      option: ""
    - command: "udm/meta_info"
      option: ""
    - command: "udm/containers"
      option: ""
    - command: "udm/types"
      option: ""
    - command: "udm/properties"
      option: ""
    - command: "udm/policies"
      option: ""
    - command: "udm/values"
      option: ""
    - command: "udm/syntax/choices/info"
      option: ""
    - command: "udm/syntax/choices"
      option: ""

{{ end }}
