---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.30.5"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"
      - "jobs/check-debian-updates.yaml"

package-helm-charts:
  variables:
    SKIP_UPDATE_HELM_VALUES: "true"

.build-matrix: &build-matrix
  - IMAGE_NAME: "data-loader-test-runner"
    KANIKO_BUILD_CONTEXT: "docker/data-loader"
    KANIKO_ARGS: "--target test"
  - IMAGE_NAME: "data-loader"
    KANIKO_BUILD_CONTEXT: "docker/data-loader"
    KANIKO_ARGS: "--target final"
  - IMAGE_NAME: "joinscript-tools"
    KANIKO_BUILD_CONTEXT: "docker/joinscript-tools"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "data-loader"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *build-matrix

test-data-loader:
  stage: "test"
  image: "${CI_REGISTRY_IMAGE}/data-loader-test-runner:${RELEASE_VERSION}"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: "never"
    - when: "on_success"
  script:
    - cd docker/data-loader
    - pytest

push-image-external:
  parallel:
    matrix: *publish-matrix

container-sign-external:
  parallel:
    matrix: *publish-matrix

check-debian-updates:
  parallel:
    matrix: *build-matrix
  variables:
    TARGET_IMAGE: "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest"

...
