---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.11.1"
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - "jobs/sphinx-docs.yaml"
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "templates/souvap.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-souvap.yaml"
      - "jobs/package-and-publish-helm-charts.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME: "data-loader-test-runner"
    KANIKO_BUILD_CONTEXT: "docker/data-loader"
    KANIKO_ARGS: "--target test"
  - IMAGE_NAME: "data-loader"
    KANIKO_BUILD_CONTEXT: "docker/data-loader"
    KANIKO_ARGS: "--target final"
  - IMAGE_NAME: "joinscript-tools"
    KANIKO_BUILD_CONTEXT: "docker/joinscript-tools"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "data-loader"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

test-data-loader:
  stage: "test"
  image: "${CI_REGISTRY_IMAGE}/data-loader-test-runner:${RELEASE_VERSION}"
  script:
    - cd docker/data-loader
    - pytest

push-image-souvap:
  parallel:
    matrix: *publish-matrix

container-sign-souvap:
  parallel:
    matrix: *publish-matrix

publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap
...
