include:
  - project: univention/customers/dataport/upx/common-ci
    file:
      # TODO: Sphinx docs inherits a stage definition from upstream,
      # has to be included before our default stages to avoid trouble.
      - jobs/sphinx-docs.yaml
      - defaults/souvap-workflow.yaml
      - defaults/stages.yaml
      - templates/kaniko.yaml
      - jobs/lint-commit-messages.yaml
      - jobs/lint-pre-commit.yaml
      - jobs/package-and-publish-helm-charts.yaml


build-data-loader-test-runner:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/data-loader-test-runner"
    KANIKO_BUILD_CONTEXT: "docker/data-loader"
    KANIKO_ARGS: "--target=test"


test-data-loader:
  stage: test
  needs:
    - job: build-data-loader-test-runner
  image: "$BUILD_IMAGE_TAG"
  script:
    - cd docker/data-loader
    - pytest


build-data-loader:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "docker/data-loader"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/data-loader"
    KANIKO_ARGS: "--target=final"


build-joinscript-tools:
  stage: build
  extends: .kaniko
  needs: []
  variables:
    KANIKO_BUILD_CONTEXT: "docker/joinscript-tools"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/joinscript-tools"


release:
  # TODO: Make a base image for this tool
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:18-buster-slim"
  stage: package
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab conventional-changelog-conventionalcommits
  script:
    - semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
