# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

---

apiVersion: "v2"
type: "application"
name: "stack-data-ums"
description: "A Helm chart to load the initial data into the UMS Stack"
home: "https://www.univention.de/"
icon: "https://www.univention.com/wp-content/themes/univention/assets/images/univention.svg"
version: "0.1.0"

dependencies:
  - name: "nubus-common"
    version: "0.28.0"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
