# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

global:
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"

stackDataContext:
  initialPasswordAdministrator: "stub_password"

stackDataUms:
  udmApiPassword: "stub_password"

...
