# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  # -- Indicates wether this chart is part of a Nubus deployment.
  nubusDeployment: false

  # -- Allows to configure extensions globally.
  extensions: []
  # -- Allows to configure system extensions globally.
  systemExtensions: []

  # -- Container registry address.
  imageRegistry: "artifacts.software-univention.de"

  # -- Credentials to fetch images from private registry.
  # Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  #
  # imagePullSecrets:
  #   - "docker-registry"
  imagePullSecrets: []

  # -- Define an ImagePullPolicy.
  #
  # Ref.: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  #
  imagePullPolicy: "IfNotPresent"

  configUcr: {}


stackDataUms:

  # -- The URL by which the UDM Rest API can be reached. Chart defaults to `http://udm-rest-api/udm/`. Nubus defaults to `http://$RELEASE_NAME-udm-rest-api/udm/`.
  udmApiUrl: ""

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: ""

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"

  # -- Enables logging of the template context used to render the template
  # files.
  #
  # Be aware that this may log sensitive information.
  logContext: false

  # -- Enables logging of the rendered templates for troubleshooting.
  #
  # Be aware that this may log sensitive information.
  logTemplate: false

  # -- Wait for the udm-rest-api to be available
  dependencyUdmApiWait: true

# -- Context used to render the data file templates in the data loader.
templateContext:
  # -- Domain name of the instance. Chart defaults to `univention-organization.intranet`
  # Example: `"example.org"`
  domainName: '{{ include "stack-data-ums.domainName" . }}'
  # TODO: Replace workaround
  # See: https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/286
  # -- Interim. The external mail domain in use. Currently required to create
  # the Administrator account. Chart defaults to `univention-organization.test`.
  externalMailDomain: '{{ include "stack-data-ums.externalMailDomain" . }}'
  # -- The initial password of the user "Administrator".
  initialPasswordAdministrator: '{{ include "stack-data-ums.initialPasswordAdministrator" . }}'
  # -- The initial password of the user "sys-idp-user.
  initialPasswordSysIdpUser: '{{ include "stack-data-ums.initialPasswordSysIdpUser" . }}'

  # TODO: This value should by default be true for a plain Nubus deployment.
  installUmcPolicies: false
  keycloakFqdn: '{{ include "stack-data-ums.keycloakFqdn" . }}'
  ldapAdminDn: '{{ include "stack-data-ums.ldapAdminDn" . }}'
  # -- Base DN of the LDAP directory. Chart defaults to `dc=univention-organization,dc=intranet`.
  # Example: `"dc=example,dc=org"`
  ldapBaseDn: '{{ include "stack-data-ums.ldapBaseDn" . }}'
  ldapDomainName: '{{ include "stack-data-ums.ldapDomainName" . }}'
  # -- Hostname of the LDAP server. Chart defaults to `ldap-server`.
  # Example: `"ucs-1234.univention.intranet"`
  ldapHost: '{{ include "stack-data-ums.ldapHost" . }}'
  # -- Hostname of the primary LDAP server. Chart defaults to `ldap-server`.
  # Example: `"ucs-1234.univention.intranet"`
  ldapMasterHost: '{{ include "stack-data-ums.ldapMasterHost" . }}'
  # -- Port to connect to the primary LDAP server. Chart defaults to `389`.
  # Example: `389`
  ldapMasterPort: '{{ include "stack-data-ums.ldapMasterPort" . }}'
  # -- Port to connect to the LDAP server. Chart defaults to `389`.
  # Example: `389`
  ldapPort: '{{ include "stack-data-ums.ldapPort" . }}'
  ldapUri: '{{ include "stack-data-ums.ldapUri" . }}'
  # -- Load development data, such as test users.
  loadDevData: true
  # -- The authentication method to use for the portal. Default is `saml`.
  portalAuthMode: '{{ include "stack-data-ums.portalAuthMode" . }}'
  portalFqdn: '{{ include "stack-data-ums.portalFqdn" . }}'
  # -- SAML Identity Provider metadata URL (as visible from the user/internet).
  # Example: `"https://id.souvap.example.org/realms/ucs/protocol/saml/descriptor"`
  samlMetadataUrl: '{{ include "stack-data-ums.samlMetadataUrl" . }}'
  # -- SAML Identity Provider metadata URL (as visible from inside the container), optional.
  # Example: `"http://keycloak:8080/realms/ucs/protocol/saml/descriptor"`
  samlMetadataUrlInternal: '{{ include "stack-data-ums.samlMetadataUrlInternal" . }}'
  samlServiceProviders: '{{ include "stack-data-ums.samlServiceProviders" . }}'
  subDomainsKeycloak: '{{ include "stack-data-ums.subDomains.keycloak" . }}'
  subDomainsPortal: '{{ include "stack-data-ums.subDomains.portal" . }}'
  udmApiCredentialSecretKey: '{{ include "stack-data-ums.udmApi.credentialSecret.key" . }}'
  udmApiCredentialSecretName: '{{ include "stack-data-ums.udmApi.credentialSecret.name" . }}'
  udmApiUrl: '{{ include "stack-data-ums.udmApiUrl" . }}'
  # -- Hostname to use for memcached of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/memcached/socket`. Chart default is `umc-server-memcached`.
  umcMemcachedHostname: '{{ include "stack-data-ums.umcMemcachedHostname" . }}'
  # -- Username to use for memcached of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/memcached/username`. UCR has no default.
  umcMemcachedUsername: '{{ include "stack-data-ums.umcMemcachedUsername" . }}'
  # This does set the UCR variable `umc/self-service/postgresql/database`. UCR default is `selfservice`. Chart default is `selfservice`.
  umcPostgresqlDatabase: '{{ include "stack-data-ums.umcPostgresqlDatabase" . }}'
  # -- Hostname to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/hostname`. UCR default is `localhost`. Chart default is `umc-server-postgresql`.
  umcPostgresqlHostname: '{{ include "stack-data-ums.umcPostgresqlHostname" . }}'
  # -- Port to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/port`. UCR default is `5432`. Chart default is `5432`.
  umcPostgresqlPort: '{{ include "stack-data-ums.umcPostgresqlPort" . }}'
  # -- Username to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/username`. UCR default is `selfservice`. Chart default is `selfservice`.
  umcPostgresqlUsername: '{{ include "stack-data-ums.umcPostgresqlUsername" . }}'
  # -- Which address scheme to consider for SAML ACS (string, comma-separated). Chart default is `https`.
  # Example: `"https, http"`
  umcSamlSchemes: '{{ include "stack-data-ums.umcSamlSchemes" . }}'
  # -- Enable the default Portal login
  enableDefaultLogin: 'false'


# TODO: the template processing of the data files is being moved into the
# run-time of the container "data-loader". "stackDataContext" will be removed
# once all files have been migrated.

stackDataContext:
  # -- Domain name of the instance. Chart defaults to `univention-organization.intranet`
  # Example: `"example.org"`
  domainname: ""
  # TODO: Replace workaround
  # See: https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/286
  # -- Interim. The external mail domain in use. Currently required to create
  # the Administrator account. Chart defaults to `univention-organization.test`.
  externalMailDomain: ""
  # -- Host name of the instance. Chart defaults to `portal`.
  # Example: `"souvap"`
  hostname: ""
  # -- Hostname of the primary LDAP server. Chart defaults to `ldap-server`.
  # Example: `"ucs-1234.univention.intranet"`
  ldapMasterHost: ""
  # -- Port to connect to the primary LDAP server. Chart defaults to `389`.
  # Example: `389`
  ldapMasterPort: ""
  # -- Hostname of the LDAP server. Chart defaults to `ldap-server`.
  # Example: `"ucs-1234.univention.intranet"`
  ldapHost: ""
  # -- Port to connect to the LDAP server. Chart defaults to `389`.
  # Example: `389`
  ldapPort: ""
  # -- Base DN of the LDAP directory. Chart defaults to `dc=univention-organization,dc=intranet`.
  # Example: `"dc=example,dc=org"`
  ldapBase: ""
  # -- DN of the UMS instance. Chart defaults to `cn=admin,dc=univention-organization,dc=intranet`.
  # Example: `"cn=ucs-1234,cn=dc,cn=computers,dc=example,dc=org"`
  ldapHostDn: ""
  # -- SAML Identity Provider metadata URL (as visible from the user/internet).
  # Example: `"https://id.souvap.example.org/realms/ucs/protocol/saml/descriptor"`
  idpSamlMetadataUrl: null
  # -- SAML Identity Provider metadata URL (as visible from inside the container), optional.
  # Example: `"http://keycloak:8080/realms/ucs/protocol/saml/descriptor"`
  idpSamlMetadataUrlInternal: ""
  # -- UMC web page title. Chart supports templated values.
  umcHtmlTitle: "Nubus Management Console"
  # -- SAML Service Provider hostname (FQDN of the UMC, which is the service provider)
  # Example: `"portal.souvap.example.org"`
  umcSamlSpFqdn: null
  # -- Which address scheme to consider for SAML ACS (string, comma-separated). Chart default is `https`.
  # Example: `"https, http"`
  umcSamlSchemes: "https"
  # -- Hostname to use for memcached of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/memcached/socket`. Chart default is `umc-server-memcached`.
  umcMemcachedHostname: ""
  # -- Username to use for memcached of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/memcached/username`. UCR has no default.
  umcMemcachedUsername: ""
  # -- Hostname to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/hostname`. UCR default is `localhost`. Chart default is `umc-server-postgresql`.
  umcPostgresqlHostname: ""
  # -- Port to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/port`. UCR default is `5432`. Chart default is `5432`.
  umcPostgresqlPort: ""
  # -- Username to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/username`. UCR default is `selfservice`. Chart default is `selfservice`.
  umcPostgresqlUsername: ""
  # This does set the UCR variable `umc/self-service/postgresql/database`. UCR default is `selfservice`. Chart default is `selfservice`.
  umcPostgresqlDatabase: ""
  # -- The FQDN of the identity provider (w/o the protocol specification).
  # Example: `"id.souvap.example.org"`
  idpFqdn: null
  # -- List of SAML Service Provider URLs which the LDAP server should trust (comma-separated).
  # Example: `"https://portal.souvap.example.org/univention/saml/metadata"`
  ldapSamlSpUrls: null
  # -- The authentication method to use for the portal. Default is `saml`.
  portalAuthMode: "saml"
  # -- The initial password of the user "Administrator".
  initialPasswordAdministrator: null
  # -- The initial password of the user "sys-idp-user.
  initialPasswordSysIdpUser: null
  # -- This parameter allows to skip the installation of the default UMC
  # policies if set to "false".
  installUmcPolicies: false
  #
  # -- Domain name of the instance. Chart defaults to `univention-organization.intranet`
  # Example: `"example.org"`
  externalDomainName: ""

  portalFqdn: 'portal.{{ include "stack-data-ums.externalDomainName" . }}'

  # -- Self-service emails: SMTP host
  smtpHost: ""
  # -- Self-service emails: SMTP port
  # (default: `587`)
  smtpPort: 587
  # -- Self-service emails: SMTP username
  smtpUser: ""
  # -- Self-service emails: SMTP via TLS
  # (default: `true`)
  smtpStartTls: true

# -- Container image configuration
image:
  registry: ""
  repository: "nubus-dev/images/data-loader"
  imagePullPolicy: ""
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null

# -- Extensions to load. This will override the configuration in
# `global.extensions`.
extensions: []

# -- Allows to configure the system extensions to load. This is intended for
# internal usage, prefer to use `extensions` for user configured extensions.
# This value will override the configuration in `global.systemExtensions`.
systemExtensions: []

# -- Additional custom annotations to add to deployed objects.
additionalAnnotations: {}

## Global values
affinity: {}
configMapUcr: '{{ include "common.names.fullname" . }}-ucr'
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
resources: {}

containerSecurityContext:
  # -- Enable container privileged escalation.
  allowPrivilegeEscalation: false
  # -- Security capabilities for container.
  capabilities:
    drop:
      - "ALL"
  # -- Enable security context.
  enabled: true
  # -- Process user id.
  runAsUser: 1000
  # -- Process group id.
  runAsGroup: 1000
  # Set Seccomp profile.
  seccompProfile:
    # -- Disallow custom Seccomp profile by setting it to RuntimeDefault.
    type: "RuntimeDefault"
  # -- Mounts the container's root filesystem as read-only.
  readOnlyRootFilesystem: true
  # -- Run container as a user.
  runAsNonRoot: true

tolerations: []

...
