---
stackDataUms:

  # -- The URL by which the UDM Rest API can be reached
  udmApiUrl: "http://udm-rest-api/udm/"

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: null

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"

  # -- Load data which is useful during development (opt-in)
  loadDevData: false

  # -- Wait for the udm-rest-api to be available
  dependencyUdmApiWait: true

stackDataContext:
  ldapBase: "dc=univention-organization,dc=intranet"

  # -- The initial password will be filled with a random value if it is not
  # provided. The password will be stored in a Kubernetes Secret if a random one
  # is generated.
  initialPasswordAdministrator: null

  # -- This parameter allows to skip the installation of the default UMC
  # policies if set to "false".
  installUmcPolicies: true



# -- Container image configuration
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/stack-data/data-loader"
  imagePullPolicy: "Always"
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null


## Global values
affinity: {}
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
tolerations: []


...
