---
stackDataUms:

  # -- The URL by which the UDM Rest API can be reached
  udmApiUrl: "http://udm-rest-api/udm/"

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: null

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"


# -- Container image configuration
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/stack-data/data-loader-bundled"
  imagePullPolicy: "Always"
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null


## Global values
affinity: {}
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
tolerations: []


...
