# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  # -- Indicates wether this chart is part of a Nubus deployment.
  nubusDeployment: false

stackDataUms:

  # -- The URL by which the UDM Rest API can be reached. Chart defaults to `http://udm-rest-api/udm/`. Nubus defaults to `http://$RELEASE_NAME-udm-rest-api/udm/`.
  udmApiUrl: ""

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: ""

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"

  # -- Load data which is useful during development (opt-in)
  loadDevData: false

  # -- Wait for the udm-rest-api to be available
  dependencyUdmApiWait: true

stackDataContext:
  # -- Domain name of the instance. Chart defaults to `univention-organization.intranet`
  # Example: `"example.org"`
  domainname: ""
  # TODO: Replace workaround
  # See: https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/286
  # -- Interim. The external mail domain in use. Currently required to create
  # the Administrator account. Chart defaults to `univention-organization.test`.
  externalMailDomain: ""
  # -- Host name of the instance. Chart defaults to `portal`.
  # Example: `"souvap"`
  hostname: ""
  # -- Hostname of the LDAP server. Chart defaults to `ldap-server`.
  # Example: `"ucs-1234.univention.intranet"`
  ldapHost: ""
  # -- Port to connect to the LDAP server. Chart defaults to `389`.
  # Example: `389`
  ldapPort: ""
  # -- Base DN of the LDAP directory. Chart defaults to `dc=univention-organization,dc=intranet`.
  # Example: `"dc=example,dc=org"`
  ldapBase: ""
  # -- DN of the UMS instance. Chart defaults to `cn=admin,dc=univention-organization,dc=intranet`.
  # Example: `"cn=ucs-1234,cn=dc,cn=computers,dc=example,dc=org"`
  ldapHostDn: ""
  # -- SAML Identity Provider metadata URL (as visible from the user/internet).
  # Example: `"https://id.souvap.example.org/realms/ucs/protocol/saml/descriptor"`
  idpSamlMetadataUrl: null
  # -- SAML Identity Provider metadata URL (as visible from inside the container), optional.
  # Example: `"http://keycloak:8080/realms/ucs/protocol/saml/descriptor"`
  idpSamlMetadataUrlInternal: ""
  # -- SAML Service Provider hostname (FQDN of the UMC, which is the service provider)
  # Example: `"portal.souvap.example.org"`
  umcSamlSpFqdn: null
  # -- Which address scheme to consider for SAML ACS (string, comma-separated). Chart default is `https`.
  # Example: `"https, http"`
  umcSamlSchemes: "https"
  # -- Hostname to use for memcached of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/memcached/socket`. Chart default is `umc-server-memcached`.
  umcMemcachedHostname: ""
  # -- Username to use for memcached of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/memcached/username`. UCR has no default. Chart default is `selfservice`.
  umcMemcachedUsername: ""
  # -- Hostname to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/hostname`. UCR default is `localhost`. Chart default is `umc-server-postgresql`.
  umcPostgresqlHostname: ""
  # -- Port to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/port`. UCR default is `5432`. Chart default is `5432`.
  umcPostgresqlPort: ""
  # -- Username to use for postgresql of the selfservice in UMC.
  # This does set the UCR variable `umc/self-service/postgresql/username`. UCR default is `selfservice`. Chart default is `selfservice`.
  umcPostgresqlUsername: ""
  # This does set the UCR variable `umc/self-service/postgresql/database`. UCR default is `selfservice`. Chart default is `selfservice`.
  umcPostgresqlDatabase: ""
  # -- The FQDN of the identity provider (w/o the protocol specification).
  # Example: `"id.souvap.example.org"`
  idpFqdn: null
  # -- List of SAML Service Provider URLs which the LDAP server should trust (comma-separated).
  # Example: `"https://portal.souvap.example.org/univention/saml/metadata"`
  ldapSamlSpUrls: null
  # -- The authentication method to use for the portal. Default is `saml`.
  portalAuthMode: "saml"
  # -- The initial password of the user "Administrator".
  initialPasswordAdministrator: null
  # -- The initial password of the user "sys-idp-user.
  initialPasswordSysIdpUser: null
  # -- This parameter allows to skip the installation of the default UMC
  # policies if set to "false".
  installUmcPolicies: true



# -- Container image configuration
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/stack-data/data-loader"
  imagePullPolicy: "Always"
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null

# -- Additional custom annotations to add to deployed objects.
additionalAnnotations: {}

## Global values
affinity: {}
configMapUcr: '{{ include "common.names.fullname" . }}-ucr'
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
resources: {}
securityContext: {}
tolerations: []

...
