# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
---

imagePullSecrets:
  - "kyverno-test"
replicaCount: 42

global:
  imageRegistry: "my_private_registry.domain.tld"
  imagePullSecrets:
    - "kyverno-test"
  imagePullPolicy: "kyverno"
  systemExtensions:
    - name: "portal"
      image:
        repository: "nubus/images/portal-extension"
        tag: "0.44.3@sha256:734efc0adda680526dde09387db964612f9e0ab020382580984488cc993c68f0"

resources:
  limits:
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

initResources:
  limits:
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

...
