# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
global:
  # -- Indicates wether this chart is part of a Nubus deployment.
  nubusDeployment: false

stackDataSwp:

  # -- The URL by which the UDM Rest API can be reached. Chart defaults to `http://udm-rest-api/udm/`. Nubus defaults to `http://$RELEASE_NAME-udm-rest-api/udm/`.
  udmApiUrl: ""

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: ""

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"

  # -- The name of the ConfigMap to import the data from
  dataConfigMapName: null

  # -- An additional set of demo users, typically supplied in a seperate values file in the form:
  # - username: dummy.user
  #   firstname: Dummy
  #   lastname: User
  #   primaryGroupCN: Domain Users
  #   password: secretPW
  demoUsers: null

  # -- Load data which is useful during development (opt-in)
  loadDevData: false

  # -- Wait for the udm-rest-api to be available
  dependencyUdmApiWait: true

  # -- Allow to configure additional data files.
  # This has to be a map from the desired filename to the content. The content has
  # to be a valid YAML stream which the data loader is able to process.
  extraDataFiles: null

  # -- Display release version and deploy date in the portal menu
  systemInformation: null

# -- Context used for rendering the data files
stackDataContext:
  # -- Base DN of the LDAP directory. Chart defaults to `dc=univention-organization,dc=intranet`.
  # Example: `"dc=example,dc=org"`
  ldapBase: ""
  ldapSystemUsers: []
  ldapSearchUsers: []
  # -- Domain name of the instance. Chart defaults to `univention-organization.intranet`
  # Example: `"example.org"`
  externalDomainName: ""
  # TODO: Replace workaround
  # See: https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/286
  # -- Interim. The external mail domain in use. Currently required to create
  # the Administrator account. Chart defaults to `univention-organization.test`.
  externalMailDomain: ""

  portalGroupwareLinkBase: 'https://webmail.{{ include "stack-data-swp.externalDomainName" . }}'
  portalFileshareLinkBase: 'https://fs.{{ include "stack-data-swp.externalDomainName" . }}'
  portalRealtimeCollaborationLinkBase: 'https://ucc.{{ include "stack-data-swp.externalDomainName" . }}'
  portalRealtimeVideoconferenceLinkBase: 'https://jitsi.{{ include "stack-data-swp.externalDomainName" . }}'
  portalManagementProjectLinkBase: 'https://project.{{ include "stack-data-swp.externalDomainName" . }}'
  portalManagementKnowledgeLinkBase: 'https://wiki.{{ include "stack-data-swp.externalDomainName" . }}'

  portalFqdn: 'portal.{{ include "stack-data-swp.externalDomainName" . }}'

  # -- Self-service emails: SMTP host
  smtpHost: null
  # -- Self-service emails: SMTP port
  # (default: `587`)
  smtpPort: 587
  # -- Self-service emails: SMTP username
  smtpUser: null
  # -- Self-service emails: SMTP via TLS
  # (default: `true`)
  smtpStartTls: true

  oxDefaultContext: "10"

  portaltileGroupUserStandard:
    - 'cn=Domain Users,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupUserAdmin:
    - 'cn=Domain Admins,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
    - 'cn=Support,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupUserAll:
    - 'cn=Domain Admins,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
    - 'cn=Domain Users,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupGroupware:
    - 'cn=managed-by-attribute-Groupware,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupFileshare:
    - 'cn=managed-by-attribute-Fileshare,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupManagementProject:
    - 'cn=managed-by-attribute-Projectmanagement,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupManagementKnowledge:
    - 'cn=managed-by-attribute-Knowledgemanagement,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupManagementLearn:
    - 'cn=managed-by-attribute-Learnmanagement,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'
  portaltileGroupLiveCollaboration:
    - 'cn=managed-by-attribute-Livecollaboration,cn=groups,{{ include "stack-data-swp.ldapBaseDn" . }}'

  # -- Portal title (Deutsch)
  portalTitleDE: "Souveräner Arbeitsplatz"

  # -- Portal title (English)
  portalTitleEN: "Sovereign Workplace"

  # -- Password for the default.user user.
  # This is only evaluated if loadDevData is set to true.
  userPassword: null
  # -- Password for the default.admin user.
  # This is only evaluated if loadDevData is set to true.
  adminPassword: null


# -- Container image configuration
image:
  registry: "artifacts.software-univention.de"
  repository: "nubus-dev/images/data-loader"
  imagePullPolicy: "IfNotPreset"
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null

# -- Additional custom annotations to add to deployed objects.
additionalAnnotations: {}

## Global values
affinity: {}
configMapUcrForced: '{{ include "common.names.fullname" . }}-ucr'
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
# -- Will be mapped into the containers which run the import job as attribute "resources".
# See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ .
resources: {}
securityContext: {}
tolerations: []

...
