# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

stackDataSwp:

  # -- The URL by which the UDM Rest API can be reached
  udmApiUrl: "http://udm-rest-api/udm/"

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: null

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"

  # -- The name of the ConfigMap to import the data from
  dataConfigMapName: null

  # -- An additional set of demo users, typically supplied in a seperate values file in the form:
  # - username: dummy.user
  #   firstname: Dummy
  #   lastname: User
  #   primaryGroupCN: Domain Users
  #   password: secretPW
  demoUsers: null

  # -- Load data which is useful during development (opt-in)
  loadDevData: false

  # -- Wait for the udm-rest-api to be available
  dependencyUdmApiWait: true

  # -- Allow to configure additional data files.
  # This has to be a map from the desired filename to the content. The content has
  # to be a valid YAML stream which the data loader is able to process.
  extraDataFiles: null

  # -- Display release version and deploy date in the portal menu
  systemInformation: null

# -- Context used for rendering the data files
stackDataContext:
  ldapBase: "dc=univention-organization,dc=intranet"
  ldapSearchUsers: []
  externalDomainName: "univention-organization.test"
  externalMailDomain: "univention-organization.test"
  portalGroupwareLinkBase: "https://webmail.{{ .Values.stackDataContext.externalDomainName }}"
  portalFileshareLinkBase: "https://fs.{{ .Values.stackDataContext.externalDomainName }}"
  portalRealtimeCollaborationLinkBase: "https://ucc.{{ .Values.stackDataContext.externalDomainName }}"
  portalRealtimeVideoconferenceLinkBase: "https://jitsi.{{ .Values.stackDataContext.externalDomainName }}"
  portalManagementProjectLinkBase: "https://project.{{ .Values.stackDataContext.externalDomainName }}"
  portalManagementKnowledgeLinkBase: "https://wiki.{{ .Values.stackDataContext.externalDomainName }}"

  portalFqdn: "portal.{{ .Values.stackDataContext.externalDomainName }}"

  # -- Self-service emails: SMTP host
  smtpHost: null
  # -- Self-service emails: SMTP port
  # (default: `587`)
  smtpPort: 587
  # -- Self-service emails: SMTP username
  smtpUser: null
  # -- Self-service emails: SMTP via TLS
  # (default: `true`)
  smtpStartTls: true

  # -- Define the default OX AppSuite Context for users
  oxDefaultContext: "1"

  portaltileGroupUserStandard:
    - "cn=Domain Users,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupUserAdmin:
    - "cn=Domain Admins,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
    - "cn=Support,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupUserAdminPreview:
    - "cn=Domain Admin Preview,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupUserAll:
    - "cn=Domain Admins,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
    - "cn=Domain Users,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupGroupware:
    - "cn=managed-by-attribute-Groupware,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupFileshare:
    - "cn=managed-by-attribute-Fileshare,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupManagementProject:
    - "cn=managed-by-attribute-Projectmanagement,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupManagementKnowledge:
    - "cn=managed-by-attribute-Knowledgemanagement,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupManagementLearn:
    - "cn=managed-by-attribute-Learnmanagement,cn=groups,{{ .Values.stackDataContext.ldapBase }}"
  portaltileGroupLiveCollaboration:
    - "cn=managed-by-attribute-Livecollaboration,cn=groups,{{ .Values.stackDataContext.ldapBase }}"

  # -- Portal title (Deutsch)
  portalTitleDE: "Souveräner Arbeitsplatz"

  # -- Portal title (English)
  portalTitleEN: "Sovereign Workplace"

  # -- Password for the default.user user.
  # This is only evaluated if loadDevData is set to true.
  userPassword: null
  # -- Password for the default.admin user.
  # This is only evaluated if loadDevData is set to true.
  adminPassword: null


# -- Container image configuration
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/stack-data/data-loader"
  imagePullPolicy: "Always"
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null

# -- Additional custom annotations to add to deployed objects.
additionalAnnotations: {}

## Global values
affinity: {}
configMapUcrForced: '{{ include "common.names.fullname" . }}-ucr'
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
# -- Will be mapped into the containers which run the import job as attribute "resources".
# See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ .
resources: {}
securityContext: {}
tolerations: []

...
