---
stackDataSwp:

  # -- The URL by which the UDM Rest API can be reached
  udmApiUrl: "http://udm-rest-api/udm/"

  # -- The username to use to connect to the UDM Rest API
  udmApiUser: "cn=admin"

  # -- The password to access the UDM Rest API
  udmApiPassword: null

  # -- The filename which contains the password
  udmApiPasswordFile: "/run/secrets/univention.de/data-loader/udm_secret"

  # -- The name of the ConfigMap to import the data from
  dataConfigMapName: null

  # -- Load data which is useful during development (opt-in)
  loadDevData: false

# -- Context used for rendering the data files
stackDataContext:
  ldapBase: "dc=univention-organization,dc=intranet"
  externalDomainName: "univention-organization.test"
  externalMailDomain: "univention-organization.test"
  portalGroupwareLinkBase: "https://webmail.{{ .Values.stackDataContext.externalDomainName }}"
  portalFileshareLinkBase: "https://fs.{{ .Values.stackDataContext.externalDomainName }}"
  portalRealtimeCollaborationLinkBase: "https://ucc.{{ .Values.stackDataContext.externalDomainName }}"
  portalRealtimeVideoconferenceLinkBase: "https://jitsi.{{ .Values.stackDataContext.externalDomainName }}"
  portalManagementProjectLinkBase: "https://project.{{ .Values.stackDataContext.externalDomainName }}"
  portalManagementKnowledgeLinkBase: "https://wiki.{{ .Values.stackDataContext.externalDomainName }}"

  oxDefaultContext: "10"


# -- Container image configuration
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/customers/dataport/upx/stack-data/data-loader"
  imagePullPolicy: "Always"
  tag: "latest"

  # -- Define image sha256 as an alternative to `tag`
  sha256: null


## Global values
affinity: {}
environment: {}
fullnameOverride: ""
mountSecrets: true
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
tolerations: []


...
