{{ with .Values.stackDataContext }}

# Source: https://git.knut.univention.de/univention/ucs/-/blob/5.0-4/base/univention-lib/shell/umc.sh#L85
# "umc_init" is called from many join scripts
---
action: create
module: container/cn
position: cn=univention,{{ .ldapBase }}
properties:
  name: UMC
---
action: create
module: container/cn
position: cn=policies,{{ .ldapBase }}
properties:
  name: UMC
  policyPath: true
---
action: create
module: container/cn
position: cn=UMC,cn=univention,{{ .ldapBase }}
properties:
  name: operations
---
action: create
module: policies/umc
position: cn=UMC,cn=policies,{{ .ldapBase }}
properties:
  name: default-umc-all
---
action: ensure_list_contains
module: groups/group
position: cn=Domain Admins,cn=groups,{{ .ldapBase }}
policies:
  policies/umc:
    - "cn=default-umc-all,cn=UMC,cn=policies,{{ .ldapBase }}"
---
action: create
module: policies/umc
position: cn=UMC,cn=policies,{{ .ldapBase }}
properties:
  name: default-umc-users
---
action: ensure_list_contains
module: groups/group
position: cn=Domain Users,cn=groups,{{ .ldapBase }}
policies:
  policies/umc:
    - "cn=default-umc-users,cn=UMC,cn=policies,{{ .ldapBase }}"

{{ end }}
