# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
# See: https://git.knut.univention.de/univention/ucs/-/blob/5.0-3/management/univention-ldap/10univention-ldap-server.inst#L254
action: "create"
module: "users/user"
position: "cn=users,{{ ldapBaseDn }}"
properties:
  username: "Administrator"
  lastname: "Administrator"

  # TODO: Workaround. We configure currently "firstname" and
  # "mailPrimaryAddress" as required via UCR settings.
  # See: https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/286
  firstname: "Admin"
  mailPrimaryAddress: "administrator@{{ externalMailDomain }}"
  password: "{{ initialPasswordAdministrator }}"
  primaryGroup: "cn=Domain Admins,cn=groups,{{ ldapBaseDn }}"
  guardianRoles:
    - "guardian:builtin:super-admin"

---
# See: https://git.knut.univention.de/univention/ucs/-/blob/5.0-3/management/univention-ldap/10univention-ldap-server.inst#L265
action: ensure_list_contains
module: groups/group
position: cn=Domain Users,cn=groups,{{ ldapBaseDn }}
properties:
  users:
    - "uid=Administrator,cn=users,{{ ldapBaseDn }}"
