{{ with .Values.stackDataContext }}

---
# See: https://git.knut.univention.de/univention/ucs/-/blob/5.0-3/management/univention-ldap/10univention-ldap-server.inst#L254
action: "create"
module: "users/user"
position: "cn=users,{{ .ldapBase }}"
properties:
  username: "Administrator"
  lastname: "Administrator"

  # TODO: Workaround. We configure currently "firstname" and
  # "mailPrimaryAddress" as required via UCR settings.
  # See: https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/286
  # firstname: "Admin"
  # mailPrimaryAddress: "administrator@{{ .externalMailDomain }}"

  password: {{ required "stackDataContext.initialPasswordAdministrator is missing" .initialPasswordAdministrator | quote }}
  primaryGroup: "cn=Domain Admins,cn=groups,{{ .ldapBase }}"
---
# See: https://git.knut.univention.de/univention/ucs/-/blob/5.0-3/management/univention-ldap/10univention-ldap-server.inst#L265
action: ensure_list_contains
module: groups/group
position: cn=Domain Users,cn=groups,{{ .ldapBase }}
properties:
  users:
    - "uid=Administrator,cn=users,{{ .ldapBase }}"

{{ end }}
