# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH

# Source: https://git.knut.univention.de/univention/ucs/-/blob/5.0-4/management/univention-management-console-module-udm/35univention-management-console-module-udm.inst
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-all"
  description: "UDM - All operations"
  flavor: ""
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-users"
  description: "UDM - Users"
  flavor: "users/user"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=users/user"
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/query"
      option: "objectType=groups/group"
    - command: "udm/properties"
      option: "objectType=groups/group"
    - command: "udm/values"
      option: "objectType=groups/group"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-groups"
  description: "UDM - Groups"
  flavor: "groups/group"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=groups/group"
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/query"
      option: "objectType=users/user"
    - command: "udm/properties"
      option: "objectType=users/user"
    - command: "udm/values"
      option: "objectType=users/user"
    - command: "udm/query"
      option: "objectType=computers/*"
    - command: "udm/properties"
      option: "objectType=computers/*"
    - command: "udm/values"
      option: "objectType=computers/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-policies"
  description: "UDM - Policies"
  flavor: "policies/policy"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/query"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-navigation"
  description: "UDM - Navigation"
  flavor: "navigation"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/get"
      option: ""
    - command: "udm/layout"
      option: ""
    - command: "udm/meta_info"
      option: ""
    - command: "udm/nav/container/query"
      option: ""
    - command: "udm/nav/object/query"
      option: ""
    - command: "udm/policies"
      option: ""
    - command: "udm/properties"
      option: ""
    - command: "udm/types"
      option: ""
    - command: "udm/values"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-navigation-full-access"
  description: "UDM - Navigation (full access)"
  flavor: "navigation"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-portal"
  description: "UDM - Portal settings"
  flavor: "settings/portal_all"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=settings/portal*"
    - command: "udm/types"
      option: ""
    - command: "udm/get"
      option: ""
    - command: "udm/put"
      option: ""
    - command: "udm/properties"
      option: ""
    - command: "udm/values"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-new-portal"
  description: "UDM - Portal"
  flavor: "portals/all"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=portals/*"
    - command: "udm/types"
      option: ""
    - command: "udm/get"
      option: ""
    - command: "udm/put"
      option: ""
    - command: "udm/properties"
      option: ""
    - command: "udm/values"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-syntax"
  description: "UDM - Syntax"
  flavor: ""
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/syntax/choices/info"
      option: ""
    - command: "udm/syntax/choices"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-validate"
  description: "UDM - Validate"
  flavor: ""
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/validate"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-reports"
  description: "UDM - Reports"
  flavor: ""
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/reports/query"
      option: ""
    - command: "udm/reports/create"
      option: ""
    - command: "udm/reports/get"
      option: ""
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-usertemplates"
  description: "UDM - Apply User Templates"
  flavor: "settings/usertemplate"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/get"
      option: ""

---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-blocklists"
  description: "UDM - Blocklists"
  flavor: "blocklists/all"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "objectType=blocklists/*"
      flavor: "blocklists/all"

---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-contacts"
  description: "UDM - Contacts"
  flavor: "users/contact"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/reports/query"
      option: ""
    - command: "udm/meta_info"
      option: ""
    - command: "udm/containers"
      option: ""
    - command: "udm/types"
      option: ""
    - command: "udm/properties"
      option: ""
    - command: "udm/layout"
      option: ""
    - command: "udm/policies"
      option: ""
    - command: "udm/values"
      option: ""
    - command: "udm/query"
      option: ""
    - command: "udm/*"
      option: "objectType=users/contact"
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-printers"
  description: "UDM - Printers"
  flavor: "shares/print"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/*"
      option: "objectType=shares/print*"
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-dhcp"
  description: "UDM - DHCP"
  flavor: "dhcp/dhcp"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "objectType=dhcp/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-dns"
  description: "UDM - DNS"
  flavor: "dns/dns"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "objectType=dns/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-mail"
  description: "UDM - Mail"
  flavor: "mail/mail"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "objectType=mail/*"
    - command: "udm/properties"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-network"
  description: "UDM - Network"
  flavor: "networks/network"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "objectType=networks/network"
    - command: "udm/properties"
      option: "objectType=policies/*"
---
action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-shares"
  description: "UDM - Shares"
  flavor: "shares/share"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "objectType=shares/share"
    - command: "udm/properties"
      option: "objectType=policies/*"

---

action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-computers"
  description: "UDM - Computers"
  flavor: "computers/computer"
  hosts: []
  objectFlag: []
  operation:
    - command: "udm/query"
      option: "objectType=policies/*"
    - command: "udm/layout"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "objectType=computers/*"
    - command: "udm/query"
      option: "objectType=groups/group"
    - command: "udm/properties"
      option: "objectType=policies/*"
    - command: "udm/*"
      option: "!objectType"
    - command: "udm/properties"
      option: "objectType=groups/group"
    - command: "udm/values"
      option: "objectType=groups/group"
---

action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "welcome-all"
  description: "Welcome"
  flavor: ""
  hosts: []
  objectFlag: []
  operation:
    - command: "welcome/*"
      option: ""

---

action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-license"
  flavor: "license-import"
  description: "UDM - License Import"
  operation:
    - command: "udm/license/*"
      option: ""
  hosts: []
  objectFlag: []

---

action: create
module: settings/umc_operationset
position: "cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
properties:
  name: "udm-request-license"
  flavor: ""
  description: "UDM - Request new license"
  operation:
    - command: "udm/request_new_license"
      option: ""
  hosts: []
  objectFlag: []

---
action: ensure_list_contains
module: policies/umc
position: "cn=default-umc-all,cn=UMC,cn=policies,{{ ldapBaseDn }}"
properties:
  allow:
    - "cn=welcome-all,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-contacts,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-groups,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-users,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-computers,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-printers,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-blocklists,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-dhcp,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-dns,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-navigation-full-access,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-mail,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-network,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-policies,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-shares,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-portal,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-new-portal,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-syntax,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-license,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-request-license,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-validate,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-reports,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
    - "cn=udm-usertemplates,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
---
action: create
module: policies/umc
position: cn=UMC,cn=policies,{{ ldapBaseDn }}
properties:
  name: default-udm-self
---
action: ensure_list_contains
module: policies/umc
position: "cn=default-udm-self,cn=UMC,cn=policies,{{ ldapBaseDn }}"
properties:
  allow:
    - "cn=udm-self,cn=operations,cn=UMC,cn=univention,{{ ldapBaseDn }}"
