# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
action: create
module: groups/group
position: cn=groups,{{ ldapBaseDn }}
properties:
  name: "LDAPSearch Users"

---
action: create
module: users/ldap
position: cn=users,{{ ldapBaseDn }}
properties:
  username: "readonly"
  lastname: "LDAP-system-User"
  password: {{ readonlyUserPassword }}
  overridePWHistory: true
  overridePWLength: true
