# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}

---
action: "create"
module: "settings/extended_attribute"
position: "cn=custom attributes,cn=univention,{{ .ldapBase }}"
properties:
  name: "guardianRole"
  tabName: "Guardian"
  shortDescription: "Roles used by Guardian for access permissions"
  translationShortDescription:
    de_DE: "Die Rollen, welche vom Guardian zur Authorisation genutzt werden."
  longDescription: "Lowercase ASCII alphanumeric string with underscores or dashes, in the format 'app:namespace:role' or 'app:namespace:role&app:namespace:context'"
  translationLongDescription:
    de_DE: "ASCII alphanumerischer Text in Kleinschrift mit Unter- und Bindestrichen im Format 'app:namespace:role' oder 'app:namespace:role&app:namespace:context'"
  module:
    - "users/user"
    - "groups/group"
  mayChange: True
  multivalue: True
  objectClass: univentionGuardianObject
  syntax: GuardianRole
  ldapMapping: univentionGuardianRole


{{ end }}
