# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

# Source: https://git.knut.univention.de/univention/ucs/-/blob/5.0-4/base/univention-lib/shell/umc.sh#L85
# "umc_init" is called from many join scripts
---
action: create
module: container/cn
position: cn=univention,{{ ldapBaseDn }}
properties:
  name: data
---
action: create
module: settings/data
position: cn=data,cn=univention,{{ ldapBaseDn }}
properties:
  name: stack-data-ums.done
  data_type: synchronization-flag
