# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
action: "create"
module: "users/user"
position: 'cn=users,{{ .context.ldapBaseDn }}'
properties:
  username: "default.user"
  firstname: "Default"
  lastname: "User"
  password: {{ .context.userPassword | quote }}
  oxContext: {{ .context.oxDefaultContext }}
  oxAccess: "opendesk_standard"
  isOxUser: True
  opendeskFileshareEnabled: True
  opendeskProjectmanagementEnabled: True
  opendeskKnowledgemanagementEnabled: True
  opendeskLivecollaborationEnabled: True
  opendeskProjectmanagementAdmin: False
  opendeskFileshareAdmin: False
  mailPrimaryAddress: "default.user@{{ .context.externalMailDomain }}"
  overridePWHistory: true
  overridePWLength: true
---
action: "create"
module: "users/user"
position: 'cn=users,{{ .context.ldapBaseDn }}'
properties:
  username: "default.admin"
  firstname: "Default"
  lastname: "Admin"
  primaryGroup: 'cn=Domain Admins,cn=groups,{{ .context.ldapBaseDn }}'
  password: {{ .context.adminPassword | quote }}
  isOxUser: False
  guardianRole:
    - "guardian:builtin:app-admin"
  mailPrimaryAddress: "default.admin@{{ .context.externalMailDomain }}"
  opendeskProjectmanagementAdmin: False
  opendeskFileshareAdmin: False
  opendeskFileshareEnabled: False
  opendeskProjectmanagementEnabled: False
  opendeskKnowledgemanagementEnabled: False
  opendeskLivecollaborationEnabled: False
  overridePWHistory: true
  overridePWLength: true
