{{ if not .Values.stackDataSwp.dataConfigMapName }}
---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-data") }}
...
{{ end }}

{{- define "stack-data-swp.configMap-data" }}
{{- /* Simulates one level of recursion

       This applies templating to the values of "stackDataContext" and then
       injects the result back into "$.top.Values" so that the values can be
       used as if Helm would apply templating to the values file.
*/ -}}
{{- $_ := set $.top.Values "stackDataContext" (fromYaml (tpl (toYaml $.top.Values.stackDataContext) $.top)) }}

{{- with .top }}
metadata:
  name: '{{ include "common.names.fullname" . }}-data'
data:
{{- range $path, $_ := $.top.Files.Glob "data-files/default/*.yaml" }}
  {{ base $path }}: |-
    # Source: {{ $path }}
{{ tpl ($.top.Files.Get $path) $.top | indent 4 }}
{{- end }}

{{- if .Values.stackDataSwp.loadDevData }}
{{- range $path, $_ := $.top.Files.Glob "data-files/dev/*.yaml" }}
  {{ base $path }}: |-
    # Source: {{ $path }}
{{ tpl ($.top.Files.Get $path) $.top | indent 4 }}
{{- end }}
{{- end }}

{{- $demoUsers := .Values.stackDataSwp.demoUsers -}}
{{- if $demoUsers }}
  demoUsers: |-
    # Source: local values file
{{- range $_, $user := $demoUsers }}
    ---
    action: "create"
    module: "users/user"
    position: "cn=users,{{ $.top.Values.stackDataContext.ldapBase }}"
    properties:
      primaryGroup: "cn={{ get $user "primaryGroupCN" }},cn=groups,{{ $.top.Values.stackDataContext.ldapBase }}"
      {{- $pure_user := omit $user "primaryGroupCN" -}}
      {{- range $key, $value := $pure_user }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    ...
{{- end }}
{{- end }}

{{- end }}
{{- end }}
