---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-attribute-to-group-mapper-hook") }}

{{- define "stack-data-swp.configMap-attribute-to-group-mapper-hook" }}
{{- with .top }}
{{- /*
    Package the Attribute to Group Mapper UDM Hook.
*/ -}}
metadata:
  name: '{{ include "common.names.fullname" . }}-attribute-to-group-mapper-hook'
binaryData:
  AttributeToGroupMapper.py: {{ .Files.Get "data-files/default/udm-plugins/AttributeToGroupMapper.py" | b64enc | quote }}
data:
  flag_to_group_mapping.json: |
    {
      "isOxUser": "managed-by-attribute-Groupware",
      "opendeskFileshareEnabled": "managed-by-attribute-Fileshare",
      "opendeskProjectmanagementEnabled": "managed-by-attribute-Projectmanagement",
      "opendeskKnowledgemanagementEnabled": "managed-by-attribute-Knowledgemanagement",
      "opendeskLivecollaborationEnabled": "managed-by-attribute-Livecollaboration"
    }
{{- end }}
{{- end }}
