# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ if not .Values.stackDataSwp.dataConfigMapName }}
---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-data") }}
...
{{ end }}

{{- define "stack-data-swp.configMap-data" }}
{{- /* Simulates one level of recursion

       This applies templating to the values of "stackDataContext" and then
       injects the result back into "$.top.Values" so that the values can be
       used as if Helm would apply templating to the values file.
*/ -}}
{{- $_ := set $.top.Values "stackDataContext" (fromYaml (tpl (toYaml $.top.Values.stackDataContext) $.top)) }}

{{- with .top }}
metadata:
  name: '{{ include "common.names.fullname" . }}-data'
data:
{{- range $path, $_ := $.top.Files.Glob "data-files/default/*.yaml" }}
  {{ base $path }}: |-
    # Source: {{ $path }}
{{ tpl ($.top.Files.Get $path) $.top | indent 4 }}
{{- end }}

{{- if .Values.stackDataSwp.loadDevData }}
{{- range $path, $_ := $.top.Files.Glob "data-files/dev/*.yaml" }}
  {{ base $path }}: |-
    # Source: {{ $path }}
{{ tpl ($.top.Files.Get $path) $.top | indent 4 }}
{{- end }}
{{- end }}

{{- if .Values.stackDataSwp.extraDataFiles }}
{{- range $filename, $filecontent := .Values.stackDataSwp.extraDataFiles }}
  {{ $filename }}: |-
{{ tpl $filecontent $.top | indent 4 }}
{{- end }}
{{- end }}

{{- $demoUsers := .Values.stackDataSwp.demoUsers -}}
{{- if $demoUsers }}
  demoUsers: |-
    # Source: local values file
{{- range $_, $user := $demoUsers }}
    ---
    action: "create"
    module: "users/user"
    position: "cn=users,{{ $.top.Values.stackDataContext.ldapBase }}"
    properties:
      primaryGroup: "cn={{ get $user "primaryGroupCN" }},cn=groups,{{ $.top.Values.stackDataContext.ldapBase }}"
      {{- $pure_user := omit $user "primaryGroupCN" -}}
      {{- range $key, $value := $pure_user }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    ...
{{- end }}
{{- end }}

{{- if .Values.stackDataSwp.systemInformation }}
  systemInformation: |-
    # Source: local values file
    ---
    action: "create_or_modify"
    module: "portals/entry"
    position: "cn=entry,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
    properties:
      name: "opendesk.sysinfo.release"
      allowedGroups: {{ toJson $.top.Values.stackDataContext.portaltileGroupUserAdmin }}
      link:
        - - "en_US"
          - "https://gitlab.opencode.de/bmi/opendesk/deployment/sovereign-workplace/-/releases"
      anonymous: false
      linkTarget: "newwindow"
      target: ""
      description:
        de_DE: "Releaseversion"
        en_US: "Release version"
      displayName:
        de_DE: "{{ .Values.stackDataSwp.systemInformation.releaseVersion }}"
        en_US: "{{ .Values.stackDataSwp.systemInformation.releaseVersion }}"
    ---
    action: "create_or_modify"
    module: "portals/entry"
    position: "cn=entry,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
    properties:
      name: "opendesk.sysinfo.deploydate"
      allowedGroups: {{ toJson $.top.Values.stackDataContext.portaltileGroupUserAdmin }}
      link:
        - - "en_US"
          - "https://gitlab.opencode.de/bmi/opendesk"
      anonymous: false
      linkTarget: "newwindow"
      target: ""
      description:
        de_DE: "Deployment Datum"
        en_US: "Deployment date"
      displayName:
        de_DE: "{{ .Values.stackDataSwp.systemInformation.deployDate }}"
        en_US: "{{ .Values.stackDataSwp.systemInformation.deployDate }}"
    ---
    action: "create"
    module: "portals/folder"
    position: "cn=folder,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
    properties:
      name: "opendesk.sysinfo"
      displayName:
        de_DE: "Systeminformation"
        en_US: "Systeminformation"
      entries:
        - "cn=opendesk.sysinfo.release,cn=entry,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
        - "cn=opendesk.sysinfo.deploydate,cn=entry,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
    ---
    action: "ensure_list_contains"
    module: "portals/portal"
    position: "cn=domain,cn=portal,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
    properties:
      menuLinks:
        - "cn=opendesk.sysinfo,cn=folder,cn=portals,cn=univention,{{ $.top.Values.stackDataContext.ldapBase }}"
    ...
{{- end }}

{{- end }}
{{- end }}
