---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-announcements") }}

{{- define "stack-data-swp.configMap-announcements" }}
{{- with .top }}
metadata:
  name: '{{ include "common.names.fullname" . }}-umc-server-announcements'

data:
  udm-portals-announcement.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <umc version="2.0">
      <module id="udm" version="1.0">
        <name></name>
        <description></description>
        <flavor id="portals/announcement" icon="portal">
          <name>Portal Announcements</name>
          <description>Managing the Univention Portal Announcements</description>
        </flavor>
        <categories>
          <category name="domain"/>
        </categories>
      </module>
    </umc>

binaryData:
  udm-portals-announcement.png: {{ .Files.Get "data-files/default/announcements/udm-portals-announcement.png" | b64enc | quote }}

{{- end }}
{{- end }}
