---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-ucr") }}

{{- define "stack-data-swp.configMap-ucr" }}
{{- with .top }}
{{- /*
  Place any UCR settings specific to the openDesk project here.
*/ -}}
metadata:
  name: '{{ include "common.names.fullname" . }}-ucr'
data:
  base.conf: |
    directory/manager/rest/ldap-connection/user-read/start-tls: 0
    directory/manager/web/modules/users/user/properties/firstname/required: true
    directory/manager/web/modules/users/user/properties/mailPrimaryAddress/required: true
    directory/manager/web/modules/users/user/properties/username/syntax: uid
    directory/manager/web/modules/users/user/search/autosearch: False
    directory/manager/web/modules/users/user/wizard/property/invite/default: True
    directory/manager/web/modules/users/user/wizard/property/overridePWLength/default: False
    directory/manager/web/modules/users/user/wizard/property/overridePWLength/visible: False
    directory/manager/web/modules/users/user/wizard/property/pwdChangeNextLogin/default: True
    directory/manager/web/modules/users/user/wizard/property/pwdChangeNextLogin/visible: False
    directory/manager/web/modules/users/user/add/default: "cn=openDesk User,cn=templates,cn=univention,{{ .Values.ldapBase }}"
    directory/manager/web/modules/wizard/disabled: No
    ldap/pw-bcrypt: true
    password/hashing/bcrypt: true
    ucs/web/theme: light
    uldap/start-tls: 0
    umc/cookie-banner/show: true
    umc/cookie-banner/text/de: Cookie Zustimmung
    umc/cookie-banner/text/de: Die Nutzung dieses Angebots ist nur möglich, wenn Cookies gespeichert und verarbeitet werden können (essenzielle Cookies). Dafür benötigen wir Ihre Zustimmung. Bitte akzeptieren Sie um fortzufahren oder schließen Sie die Seite.
    umc/cookie-banner/text/en: Usage of this site is only possible by storing and processing cookie information (essential cookies). We require your consent. Please accept to continue or close the page.
    umc/cookie-banner/title/en: Cookie Consent
    umc/http/cookie/samesite: Strict
    umc/http/enforce-secure-cookie: true
    umc/login/password-complexity-message/de: Das Passwort muss den folgenden Anforderungen entsprechen:<br><ul><li>Mindestlänge: 8 Zeichen</li></ul>Anmerkung: Wird befinden uns nicht in einer Produktivumgebung.
    umc/login/password-complexity-message/en: Password must comply with the following rules:<br><ul><li>Minimum length: 8 characters</li></ul>Note: We are in a non production (dev/test/demo) system.
    umc/module/udm/oxmail/oxcontext/disabled: True
    umc/module/udm/portals/all/disabled: True
    umc/web/piwik: false
{{- end }}
{{- end }}
...
