# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-ucr") }}

{{- define "stack-data-swp.configMap-ucr" }}
{{- with .top }}
{{- /*
  Place any UCR settings specific to the openDesk project here.
*/ -}}
metadata:
  name: '{{ include "common.names.fullname" . }}-ucr'
data:
  base.conf: |-
    directory/manager/rest/ldap-connection/user-read/start-tls: 0
    directory/manager/web/modules/users/user/add/default: cn=openDesk User,cn=templates,cn=univention,{{ .Values.stackDataContext.ldapBase }}
    directory/manager/web/modules/users/user/properties/description/syntax: TextArea
    directory/manager/web/modules/users/user/properties/firstname/required: true
    directory/manager/web/modules/users/user/properties/mailPrimaryAddress/required: true
    directory/manager/web/modules/users/user/properties/username/syntax: uid
    directory/manager/web/modules/users/user/search/autosearch: False
    directory/manager/web/modules/users/user/wizard/property/invite/default: True
    directory/manager/web/modules/users/user/wizard/property/overridePWLength/default: False
    directory/manager/web/modules/users/user/wizard/property/overridePWLength/visible: False
    directory/manager/web/modules/users/user/wizard/property/pwdChangeNextLogin/default: True
    directory/manager/web/modules/users/user/wizard/property/pwdChangeNextLogin/visible: False
    directory/manager/web/modules/wizard/disabled: No
    directory/manager/starttls: 0
    ldap/pw-bcrypt: true
    password/hashing/bcrypt: true
    # Sets the minimum password length
    password/quality/length/min: 8
    # Sets required chars for setting new passwords
    # password/quality/required/chars:
    # Sets forbidden chars for setting new passwords
    # password/quality/forbidden/chars:
    # Sets the minimum number of digits in the new password
    # password/quality/credit/digits: 1
    # Sets the minimum number of upper case letters
    # password/quality/credit/upper: 0
    # Sets the minimum number of chars wich are neither digits nor letters
    # password/quality/credit/other: 0
    # Sets the minimum number of lower case letters
    # password/quality/credit/lower: 1
    # Sets the microsoft policy complexity criteria. If 1,true or yes this
    # will be on top of the default python-cracklib. If sufficient only ms
    # policy complexity will be used and if false only python-cracklib will
    # be used.
    password/quality/mspolicy: false
    self-service/ldap_attributes: jpegPhoto,description,title,givenName,sn,displayName,initials,univentionBirthday,o,street,postalCode,l
    self-service/udm_attributes: jpegPhoto,description,title,firstname,lastname,displayName,initials,birthday,organisation,street,postcode,city
    self-service/udm_attributes/title/readonly: true
    self-service/udm_attributes/firstname/readonly: true
    self-service/udm_attributes/lastname/readonly: true
    self-service/udm_attributes/displayName/readonly: true
    self-service/udm_attributes/birthday/readonly: true
    self-service/udm_attributes/organisation/readonly: true
    self-service/udm_attributes/street/readonly: true
    self-service/udm_attributes/postcode/readonly: true
    self-service/udm_attributes/city/readonly: true
    self-service/udm_attributes/departmentNumber/readonly: true
    self-service/udm_attributes/employeeType/readonly: true
    self-service/udm_attributes/employeeNumber/readonly: true
    ucs/web/theme: light
    umc/cookie-banner/show: false
    umc/http/cookie/samesite: Strict
    umc/http/enforce-secure-cookie: true
    umc/login/password-complexity-message/de: Das Passwort muss den folgenden Anforderungen entsprechen:<br><ul><li>Mindestlänge: 8 Zeichen</li></ul>Anmerkung: Wird befinden uns nicht in einer Produktivumgebung.
    umc/login/password-complexity-message/en: Password must comply with the following rules:<br><ul><li>Minimum length: 8 characters</li></ul>Note: We are in a non production (dev/test/demo) system.
    umc/module/udm/oxmail/oxcontext/disabled: True
    umc/module/udm/portals/all/disabled: True
    umc/self-service/account-verification/email/webserver_address: {{ .Values.stackDataContext.portalFqdn }}
    umc/self-service/content-security-policy/frame-ancestors: 'self'
    umc/self-service/passwordreset/email/sender_address: Password Reset Service <noreply@{{ .Values.stackDataContext.externalMailDomain }}>
    umc/self-service/passwordreset/email/server: {{ .Values.stackDataContext.smtpHost }}
    umc/self-service/passwordreset/email/server/port: {{ .Values.stackDataContext.smtpPort }}
    umc/self-service/passwordreset/email/server/user: {{ .Values.stackDataContext.smtpUser }}
    umc/self-service/passwordreset/email/server/starttls: {{ .Values.stackDataContext.smtpStartTls }}
    umc/self-service/passwordreset/email/text_file: /usr/share/univention-self-service/email_bodies/passwordreset_email_body.txt
    umc/self-service/passwordreset/email/webserver_address: {{ .Values.stackDataContext.portalFqdn }}
    umc/self-service/passwordreset/token_validity_period: 172800
    umc/self-service/profiledata/enabled: true
    umc/web/piwik: false
{{- end }}
{{- end }}
...
