---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-swp.configMap-branding") }}

{{- define "stack-data-swp.configMap-branding" }}
{{- with .top }}
{{- /*
  Apply SWP branding modifications to umc-server container.
*/ -}}
metadata:
  name: '{{ include "common.names.fullname" . }}-branding'
binaryData:
  custom.css: {{ .Files.Get "data-files/default/branding-swp/custom.css" | b64enc | quote }}
  favicon.ico: {{ .Files.Get "data-files/default/branding-swp/favicon.ico" | b64enc | quote }}
  logo.svg: {{ .Files.Get "data-files/default/branding-swp/logo.svg" | b64enc | quote }}
  logo_small_border.svg: {{ .Files.Get "data-files/default/branding-swp/logo_small_border.svg" | b64enc | quote }}
  logo_small_border_white.svg: {{ .Files.Get "data-files/default/branding-swp/logo_small_border_white.svg" | b64enc | quote }}
  portal_background_image.png: {{ .Files.Get "data-files/default/branding-swp/portal_background_image.png" | b64enc | quote }}
  portal_background_image.svg: {{ .Files.Get "data-files/default/branding-swp/portal_background_image.svg" | b64enc | quote }}

{{- end }}
{{- end }}
