---
{{ include "common.secret" (dict "top" . "overrides" "stack-data-swp.secret") }}

{{- define "stack-data-swp.secret" }}
{{- with .top }}
data:
  udm_secret: {{ .Values.stackDataSwp.udmApiPassword | b64enc | quote }}
{{- end }}
{{- end }}
---
