# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
data:
  UDM_API_URL: {{ tpl
    ( required
      "The UDM Rest API connection has to be configured, see udm.connection.url."
      ( coalesce .Values.udm.connection.url ((.Values.global.udm).connection).url )
    ) . | quote }}
  UDM_API_USER: {{ tpl
    ( required
      "A UDM username is required, see parameter udm.auth.username"
      .Values.udm.auth.username
    ) . | quote }}
  UDM_API_PASSWORD_FILE: "/run/secrets/univention.de/data-loader/udm_secret"
  UDM_API_PORT: {{ include "stack-data-ums.udmApiPort" . | quote }}
