# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
data:
  UDM_API_URL: {{ include "stack-data-ums.udmApiUrl" . | quote }}
  UDM_API_USER: {{ tpl
    ( required
      "A UDM username has to be supplied, see parameter udm.auth.username"
      .Values.udm.auth.username
    ) . | quote }}
  UDM_API_PASSWORD_FILE: "{{ .Values.stackDataUms.udmApiPasswordFile }}"
  UDM_API_PORT: {{ include "stack-data-ums.udmApiPort" . | quote }}
