# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "stack-data-ums.configMap") }}

{{- define "stack-data-ums.configMap" }}
{{- with .top }}
data:
  UDM_API_URL: "{{ .Values.stackDataUms.udmApiUrl }}"
  UDM_API_USER: "{{ .Values.stackDataUms.udmApiUser }}"
  UDM_API_PASSWORD_FILE: "{{ .Values.stackDataUms.udmApiPasswordFile }}"
{{- end }}
{{- end }}
...
