# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}-context"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  # TODO: Think it would be better to render the "stackDataContext" directly to
  # yaml.
  context.yaml: |
    domainname: {{ include "stack-data-ums.domainName" . | quote }}
    ldapBaseDn: {{ include "stack-data-ums.ldapBaseDn" . | quote }}
    # TODO: This would have to come from somewhere
    oxDefaultContext: "10"
    externalMailDomain: {{ include "stack-data-ums.externalMailDomain" . | quote }}


    # TODO: Below are openDesk specific settings, these would have to be
    # configured from openDesk via the values.

    ldapSystemUsers: []
    ldapSearchUsers: []

    userPassword: {{ .Values.stackDataContext.userPassword | quote }}
    adminPassword: {{ .Values.stackDataContext.adminPassword | quote }}

    portalTitleDE: "Souveräner Arbeitsplatz"
    portalTitleEN: "Sovereign Workplace"

    # TODO: Unclear why these are not directly embedded in the yaml file, in
    # openDesk this is typically stable data and customizations would be made
    # with another layer on top.
    portaltileGroupUserStandard:
      - 'cn=Domain Users,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupUserAdmin:
      - 'cn=Domain Admins,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
      - 'cn=Support,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupUserAll:
      - 'cn=Domain Admins,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
      - 'cn=Domain Users,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupGroupware:
      - 'cn=managed-by-attribute-Groupware,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupFileshare:
      - 'cn=managed-by-attribute-Fileshare,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupManagementProject:
      - 'cn=managed-by-attribute-Projectmanagement,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupManagementKnowledge:
      - 'cn=managed-by-attribute-Knowledgemanagement,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupManagementLearn:
      - 'cn=managed-by-attribute-Learnmanagement,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'
    portaltileGroupLiveCollaboration:
      - 'cn=managed-by-attribute-Livecollaboration,cn=groups,{{ include "stack-data-ums.ldapBaseDn" . }}'

    portalGroupwareLinkBase: 'https://webmail.{{ include "stack-data-ums.domainName" . }}'
    portalFileshareLinkBase: 'https://fs.{{ include "stack-data-ums.domainName" . }}'
    portalRealtimeCollaborationLinkBase: 'https://ucc.{{ include "stack-data-ums.domainName" . }}'
    portalRealtimeVideoconferenceLinkBase: 'https://jitsi.{{ include "stack-data-ums.domainName" . }}'
    portalManagementProjectLinkBase: 'https://project.{{ include "stack-data-ums.domainName" . }}'
    portalManagementKnowledgeLinkBase: 'https://wiki.{{ include "stack-data-ums.domainName" . }}'

    portalFqdn: 'portal.{{ include "stack-data-ums.domainName" . }}'
