# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}-context"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # NOTE: We cannot use the `toYaml` function to build the context, as it gets
  # templated from _helpers.tpl
  context.yaml: |
    ldapUri: {{ include "stack-data-ums.ldapUri" . }}
    ldapHost: {{ include "stack-data-ums.ldapHost" . }}
    ldapPort: {{ include "stack-data-ums.ldapPort" . }}
    ldapMasterHost: {{ include "stack-data-ums.ldapMasterHost" . }}
    ldapMasterPort: {{ include "stack-data-ums.ldapMasterPort" . }}
    ldapBaseDn: {{ include "stack-data-ums.ldapBaseDn" . }}
    samlServiceProviders: {{ include "stack-data-ums.samlServiceProviders" . }}
    samlMetadataUrl: {{ include "stack-data-ums.samlMetadataUrl" . }}
    samlMetadataUrlInternal: {{ include "stack-data-ums.samlMetadataUrlInternal" . }}
    ldapDomainName: {{ include "stack-data-ums.ldapDomainName" . }}
    ldapAdminDn: {{ include "stack-data-ums.ldapAdminDn" . }}
    udmApiUrl: {{ include "stack-data-ums.udmApiUrl" . }}
    umcPostgresqlHostname: {{ include "stack-data-ums.umcPostgresqlHostname" . }}
    umcPostgresqlPort: {{ include "stack-data-ums.umcPostgresqlPort" . }}
    umcPostgresqlUsername: {{ include "stack-data-ums.umcPostgresqlUsername" . }}
    umcPostgresqlDatabase: {{ include "stack-data-ums.umcPostgresqlDatabase" . }}
    umcMemcachedHostname: {{ include "stack-data-ums.umcMemcachedHostname" . }}
    umcMemcachedUsername: {{ include "stack-data-ums.umcMemcachedUsername" . }}
    domainName: {{ include "stack-data-ums.domainName" . }}
    externalMailDomain: {{ include "stack-data-ums.externalMailDomain" . }}
    subDomainsPortal: {{ include "stack-data-ums.subDomains.portal" . }}
    subDomainsKeycloak: {{ include "stack-data-ums.subDomains.keycloak" . }}
    keycloakFqdn: {{ include "stack-data-ums.keycloakFqdn" . }}
    portalFqdn: {{ include "stack-data-ums.portalFqdn" . }}
    portalAuthMode: {{ include "stack-data-ums.portalAuthMode" . }}
    umcSamlSchemes: {{ include "stack-data-ums.umcSamlSchemes" . }}
    udmApiCredentialSecretName: {{ include "stack-data-ums.udmApi.credentialSecret.name" . }}
    udmApiCredentialSecretKey: {{ include "stack-data-ums.udmApi.credentialSecret.key" . }}
    {{- if $.Values.global.nubusDeployment }}
    initialPasswordAdministrator: {{ include "nubusTemplates.credentials.ldap.users.admin.password" $ | quote }}
    initialPasswordSysIdpUser: {{ include "nubusTemplates.credentials.ldap.users.idp.password" $ | quote }}
    {{- else }}
    initialPasswordAdministrator: {{ required "stackDataContext.initialPasswordAdministrator is missing" .Values.stackDataContext.initialPasswordAdministrator | quote }}
    initialPasswordSysIdpUser: {{ required "stackDataContext.initialPasswordSysIdpUser is missing" .Values.stackDataContext.initialPasswordSysIdpUser | quote }}
    {{- end }}
    {{- if .Values.stackDataContext.installUmcPolicies }}
    installUmcPolicies: {{ .Values.stackDataContext.installUmcPolicies }}
    {{- end }}
    {{- if .Values.customContext }}
    {{- range $key, $value := .Values.extraContext }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
...
