# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.secret" (dict "top" . "overrides" "stack-data-ums.secret") }}

{{- define "stack-data-ums.secret" }}
{{- with .top }}
stringData:
  udm_secret: {{ .Values.stackDataUms.udmApiPassword | quote }}
{{- end }}
{{- end }}
...
