# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}-context"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  # TODO: Think it would be better to render the "stackDataContext" directly to
  # yaml.
  context.yaml: |
    domainname: {{ include "stack-data-ums.domainName" . | quote }}
    ldapBaseDn: {{ include "stack-data-ums.ldapBaseDn" . | quote }}
    # TODO: This would have to come from somewhere
    oxDefaultContext: "10"
    externalMailDomain: {{ include "stack-data-ums.externalMailDomain" . | quote }}
