# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

---
{{- /*
The password value is currently required in two places:

1. In the "templateContext" so that the user can be created with the password.

2. In the created "Secret" for the user "svc-portal-server", so that this
   "Secret" can be used by the chart "portal-server" via the "existingSecret"
   configuration.
*/}}
{{- $passwordSvcPortalServer := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "svc-portal-server" "context" .))
    "key" "password"
    "username" "svc-portal-server"
    "providedValues" (list "templateContext.svcPortalServerUserPassword")
    "context" .
  )
}}

{{- /* Workaround to ensure that generated values are available in the template context. */}}
{{- $_ := set .Values.templateContext "svcPortalServerUserPassword" $passwordSvcPortalServer }}

kind: "Secret"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}-context"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
type: Opaque
stringData:
  context.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.templateContext "context" . ) | nindent 4 }}

---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "svc-portal-server" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- $extraAnnotations := dict }}
  {{- if (.Values.global.secrets).keep }}
    {{- $_ := set $extraAnnotations "helm.sh/resource-policy" "keep" }}
  {{- end }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list $extraAnnotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
type: Opaque
stringData:
  password: {{ $passwordSvcPortalServer | quote }}
