{{ with .Values.stackDataContext }}
---
action: create
module: users/user
position: cn=users,{{ .ldapBase }}
properties:
  username: "test.user"
  firstname: "test"
  lastname: "user"
  password: "SWPtester"
  # TODO: Provide this value
  # oxContext: {{ .oxDefaultContext }}

  # TODO: The following depend on issue
  # https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/168
  # isOxUser: "OK"
  # swpFileshareEnabled: "TRUE"
  # swpProjectmanagementEnabled: "TRUE"
  # swpKnowledgemanagementEnabled: "TRUE"
  # swpLivecollaborationEnabled: "TRUE"

  # TODO: Provide this value
  # mailPrimaryAddress: "test.user@{{ .externalMailDomain }}"
---
action: create
module: users/user
position: cn=users,{{ .ldapBase }}
properties:
  username: "test.admin"
  firstname: "test"
  lastname: "admin"
  primaryGroup: "cn=Domain Admins,cn=groups,{{ .ldapBase }}"
  password: "SWPtester"
  # TODO: Provide this value
  # mailPrimaryAddress: "test.user@{{ .externalMailDomain }}"
{{ end }}
