{{ with .Values.stackDataContext }}
---
action: "create"
module: "users/user"
position: "cn=users,{{ .ldapBase }}"
properties:
  username: "default.user"
  firstname: "test"
  lastname: "user"
  password: {{ required "Please set a password for the default user" .userPassword | quote }}
  # TODO: Provide this value
  # oxContext: {{ .oxDefaultContext }}

  # TODO: The following depend on issue
  # https://git.knut.univention.de/univention/customers/dataport/team-souvap/-/issues/168
  # isOxUser: "OK"
  # swpFileshareEnabled: "TRUE"
  # swpProjectmanagementEnabled: "TRUE"
  # swpKnowledgemanagementEnabled: "TRUE"
  # swpLivecollaborationEnabled: "TRUE"

  mailPrimaryAddress: "test.user@{{ .externalMailDomain }}"
---
action: "create"
module: "users/user"
position: "cn=users,{{ .ldapBase }}"
properties:
  username: "default.admin"
  firstname: "test"
  lastname: "admin"
  primaryGroup: "cn=Domain Admins,cn=groups,{{ .ldapBase }}"
  password: {{ required "Please set a password for the default user" .adminPassword | quote }}
  mailPrimaryAddress: "test.admin@{{ .externalMailDomain }}"
{{ end }}
