{{ with .Values.stackDataContext }}
---
action: "create"
module: "users/user"
position: "cn=users,{{ .ldapBase }}"
properties:
  username: "default.user"
  firstname: "Default"
  lastname: "User"
  password: {{ required "Please set a password for the default user" .userPassword | quote }}
  oxContext: {{ .oxDefaultContext }}
  oxAccess: "opendesk_standard"
  isOxUser: True
  opendeskFileshareEnabled: True
  opendeskProjectmanagementEnabled: True
  opendeskKnowledgemanagementEnabled: True
  opendeskLivecollaborationEnabled: True
  opendeskProjectmanagementAdmin: False
  mailPrimaryAddress: "default.user@{{ .externalMailDomain }}"
---
action: "create"
module: "users/user"
position: "cn=users,{{ .ldapBase }}"
properties:
  username: "default.admin"
  firstname: "Default"
  lastname: "Admin"
  primaryGroup: "cn=Domain Admins,cn=groups,{{ .ldapBase }}"
  password: {{ required "Please set a password for the default user" .adminPassword | quote }}
  isOxUser: False
  guardianRole:
    - "guardian:builtin:app-admin"
  mailPrimaryAddress: "default.admin@{{ .externalMailDomain }}"
  opendeskProjectmanagementAdmin: True
  opendeskFileshareEnabled: False
  opendeskProjectmanagementEnabled: False
  opendeskKnowledgemanagementEnabled: False
  opendeskLivecollaborationEnabled: False
{{ end }}
