# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

{{ with .Values.stackDataContext }}
---
action: "create"
module: "users/user"
position: 'cn=users,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  username: "default.user"
  firstname: "Default"
  lastname: "User"
  {{- if $.Values.global.nubusDeployment }}
  password: {{ include "nubusTemplates.credentials.ldap.users.idp.password" $ | quote }}
  {{- else }}
  password: {{ required "Please set a password for the default user" .userPassword | quote }}
  {{- end }}
  oxContext: {{ .oxDefaultContext }}
  oxAccess: "opendesk_standard"
  isOxUser: True
  opendeskFileshareEnabled: True
  opendeskProjectmanagementEnabled: True
  opendeskKnowledgemanagementEnabled: True
  opendeskLivecollaborationEnabled: True
  opendeskProjectmanagementAdmin: False
  opendeskFileshareAdmin: False
  mailPrimaryAddress: "default.user@{{ include "stack-data-swp.externalMailDomain" $ }}"
  overridePWHistory: true
  overridePWLength: true
---
action: "create"
module: "users/user"
position: 'cn=users,{{ include "stack-data-swp.ldapBaseDn" $ }}'
properties:
  username: "default.admin"
  firstname: "Default"
  lastname: "Admin"
  primaryGroup: 'cn=Domain Admins,cn=groups,{{ include "stack-data-swp.ldapBaseDn" $ }}'
  {{- if $.Values.global.nubusDeployment }}
  password: {{ include "nubusTemplates.credentials.ldap.users.admin.password" $ | quote }}
  {{- else }}
  password: {{ required "Please set a password for the default user" .adminPassword | quote }}
  {{- end }}
  isOxUser: False
  guardianRole:
    - "guardian:builtin:app-admin"
  mailPrimaryAddress: "default.admin@{{ include "stack-data-swp.externalMailDomain" $ }}"
  opendeskProjectmanagementAdmin: False
  opendeskFileshareAdmin: False
  opendeskFileshareEnabled: False
  opendeskProjectmanagementEnabled: False
  opendeskKnowledgemanagementEnabled: False
  opendeskLivecollaborationEnabled: False
  overridePWHistory: true
  overridePWLength: true
{{ end }}
