{{ with .Values.stackDataContext }}

# TODO: Remove once the component groups are supported into the container Stack
#
# For now this does make all entries visible to all users to simplify testing in
# development deployments.

---
action: "ensure_list_contains"
module: "groups/group"
position: "cn=managed-by-attribute-Groupware,cn=groups,{{ .ldapBase }}"
properties:
  users:
    - "uid=test.user,cn=users,{{ .ldapBase }}"
---
action: "ensure_list_contains"
module: "groups/group"
position: "cn=managed-by-attribute-Fileshare,cn=groups,{{ .ldapBase }}"
properties:
  users:
    - "uid=test.user,cn=users,{{ .ldapBase }}"
---
action: "ensure_list_contains"
module: "groups/group"
position: "cn=managed-by-attribute-Projectmanagement,cn=groups,{{ .ldapBase }}"
properties:
  users:
    - "uid=test.user,cn=users,{{ .ldapBase }}"
---
action: "ensure_list_contains"
module: "groups/group"
position: "cn=managed-by-attribute-Knowledgemanagement,cn=groups,{{ .ldapBase }}"
properties:
  users:
    - "uid=test.user,cn=users,{{ .ldapBase }}"
---
action: "ensure_list_contains"
module: "groups/group"
position: "cn=managed-by-attribute-Livecollaboration,cn=groups,{{ .ldapBase }}"
properties:
  users:
    - "uid=test.user,cn=users,{{ .ldapBase }}"

{{ end }}
